### ISSUE TITLE
Question: How do I run /sbin/my_init as a different USER?

### ISSUE THREAD

**Issue by jbkc85** [phusion/baseimage-docker#264]
I apologize if I missed this particular issue, but I am trying to run /sbin/my_init (the CMD) in my Dockerfile as a USER that is not 'root'.  I keep getting the following error:

```
myuser@b4944d852d6d:/$ /sbin/my_init
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 346, in <module>
    main(args)
  File "/sbin/my_init", line 264, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 65, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 51, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
```

I have already tried adjusting the permissions of /etc/container_environment, including the .json and .sh files but nothing seems to work.  Has anyone ran into this issue?  Does the /sbin/my_init even support running as a user other than root?

Thanks,
Jason Cameron

**Comment by FooBarWidget** [comment]
You cannot. `my_init` requires root privileges. But what you can do is having subprocesses run as a different user using the `setuser` tool.

**Comment by jacknlliu** [comment]
This seems that `baseimage` can not startup  with non-root user. Startup as root user is not a good way for many docker image.

**Comment by FooBarWidget** [comment]
It is true that containers should run with the least privilege possible. While `my_init` itself requires root privileges, it allows -- and encourages -- you to run all other code, e.g. your own apps, with non-root privileges and provides tools to make that easy. See my comment above.

It literally isn't possible to do the things `my_init` does -- namely ensuring a clean exit by killing all processes at termination -- without root privileges. This is a limitation imposed by the kernel, and unfortunately there is nothing we can do about that.

And the way `my_init` works is not all that strange, and is quite common in Unix applications. For example many web servers, such as Nginx, also require root privileges. They do the bare minimum they need to do with root privileges -- namely binding to port 80 -- and then they drop their privileges to a normal user. `my_init` is similar: it does very few things by itself, and it encourages the user to run all their own code with non-root privileges.

**Comment by jacknlliu** [comment]
@FooBarWidget Thank you very much for your reply.  If I want a container startup with a non-user in interactive TTY which `bash` running on, is this context  possible with `my_init`?

**Comment by FooBarWidget** [comment]
`docker run -ti --rm phusion/baseimage /sbin/my_init -- setuser
<normalusername> bash`

Sent from my Android phone.

Op 17 mei 2017 11:13 schreef "Jack Liu" <notifications@github.com>:

**Comment by jacknlliu** [comment]
@FooBarWidget  It works as I hope.  

And then I try to put `/sbin/my_init -- setuser <normalusername> bash` in `CMD`  in Dockerfile like this,
```
CMD ["/sbin/my_init","--", "setuser myself_name bash"]
```
which will avoid users touch this command when using my container, but the bash exit rather than act in interactive mode. Could you give me some suggestions for this context? Thank you in advance!

**Comment by FooBarWidget** [comment]
~~~
CMD ["/sbin/my_init","--", "setuser myself_name bash"]
~~~

This is not the correct way to pass parameters. You are passing the "setuser username bash" thing as a single parameters. They should be separate:

~~~
CMD ["/sbin/my_init","--", "setuser", "myself_name", "bash"]
~~~

**Comment by jacknlliu** [comment]
@FooBarWidget Thank you very much! Now everything works!

**Comment by edwardmp** [comment]
@FooBarWidget I actually ran into a similar issue.
I use Heroku Docker containers, and you simply can not run anything as root.

I tried ` /sbin/my_init -- /sbin/setuser {my non root user}` but this leads to:

```
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 353, in <module>
    main(args)
  File "/sbin/my_init", line 271, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 65, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 51, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
```

Can I conclude from your answer that this would make Passenger unusable when using Docker on Heroku (or any other platform that does not allow you to use the root user)?

**Comment by leifcr** [comment]
@FooBarWidget Same as @edwardmp, this does not work on most PaaS (e.g. openshift online)

**Comment by edwardmp** [comment]
@leifcr you can actually run passender standalone as non root. Just not with nginx in front of it

**Comment by jacknlliu** [comment]
It seems that `/sbin/my_init` startup with root user, but when container exit it just has non-root privilege.  So `/sbin/my_init`failed to reap some processes in this context.

**Comment by Theaxiom** [comment]
@jacknlliu I don't understand how that is possible...

**Comment by jacknlliu** [comment]
@Theaxiom  I just made a guess for `PermissionError: [Errno 13] Permission denied: /etc/container_environment` which mentioned by @edwardmp .

**Comment by alanjds** [comment]
Could this be solved by having a `my_init` user owning the `/etc/container_environment` stuff?

**Comment by fabriciolemos** [comment]
I'm having this same error running on OpenShift. Is there any alternative? Running as root is not an option for my environment.

**Comment by Theaxiom** [comment]
I don't really have a solution coming to mind at this point in time.

**Comment by afraca** [comment]
Just to add some information:
https://laradock.io uses this as the base image for the workspace container. I tried to run some commands (`composer install` etc) in there by first switching to non-root user, but then it fails.
Ill guess I just have to specify for each command to run it as the non-root user?

**Comment by winstxnhdw** [comment]
Does phusion still not support running as non-root? This issue blocks the possibility of running any image based on phusion on any PaaS..
